[package]
name = "ibc"
version = "0.1.0"
authors = ["Filip Toth <filip.toth@accelley.com>"]
edition="2021"

[dependencies]
async-recursion = "1.1.1"
async-trait = "0.1.85"
tokio = { version = "1.43.0", features = ["full"] }
