// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,true:30, false:30, if:32, IF:32, then:32, THEN:32, end:32, END:32, else:32, ELSE:32, output:32, OUTPUT:32, function:32, FUNCTION:32, return:32, RETURN:32, not:32, NOT:32, Void:34, Int:34, String:34, Boolean:34}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!QQYQPOOOOQO'#Ca'#CaOOQO'#Cb'#CbOOQO'#Cc'#CcOOQO'#C_'#C_OOQO'#Cg'#CgQYQPOOOOQO-E6e-E6e",
  stateData: "q~O^OSPOS~OSSOWSOXSOYSO_PO`QOaRO~O",
  goto: "k[PPP]PaaaPPPeTTOUTSOUQUORVU",
  nodeNames: "⚠ LineComment Program Atom Identifier Boolean Keyword TypeAnnotation String Number Operator",
  maxTerm: 17,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%]~R_XY!QYZ!Q]^!Qpq!Qrs!cst$Pz{$h{|$h}!O$h!P!Q$h!Q![$m!_!`$u!c!}$}#R#S$}#T#o$}~!VS^~XY!QYZ!Q]^!Qpq!Q~!fVOr!crs!{s#O!c#O#P#Q#P;'S!c;'S;=`#y<%lO!c~#QOW~~#TRO;'S!c;'S;=`#^;=`O!c~#aWOr!crs!{s#O!c#O#P#Q#P;'S!c;'S;=`#y;=`<%l!c<%lO!c~#|P;=`<%l!c~$USP~OY$PZ;'S$P;'S;=`$b<%lO$P~$eP;=`<%l$P~$mOY~~$rPX~!Q![$m~$zPY~!_!`$h~%SRS~!c!}$}#R#S$}#T#o$}",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 4, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
