// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,if:74, IF:74, true:76, false:76, Void:78, Int:78, String:78, Boolean:78, not:80, NOT:80, then:82, THEN:82, else:84, ELSE:84, end:86, END:86, function:88, FUNCTION:88, output:94, OUTPUT:94, return:96, RETURN:96}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")YO}QPOOOOQO'#Cb'#CbOOQO'#Ce'#CeOOQO'#Ci'#CiOOQO'#Cj'#CjO!UQPO'#CdOOQO'#Cd'#CdO#VQPO'#CaOOQO'#Co'#CoO#qQPO'#CnOOQO'#Cu'#CuO#vQPO'#CtOOQO'#Cw'#CwO#vQPO'#CvOOQO'#Cz'#CzOOQO'#C`'#C`OOQO'#C{'#C{O$_QPO'#C_QOQPOOO#vQPO,59dOOQO'#C|'#C|O#VQPO,58{OOQO'#Ck'#CkO$lQPO,58{O$vQPO,59YOOQO,59`,59`OOQO,59b,59bOOQO-E6y-E6yOOQO1G/O1G/OOOQO-E6z-E6zO$lQPO1G.gO${QPO1G.gO%TQPO'#CrO$oQPO1G.tO${QPO7+$ROOQO'#Cl'#ClOOQO'#Cm'#CmO%]QPO7+$RO$oQPO7+$RO%bQPO'#CsOOQO,59^,59^O%gQPO,59^O%OQPO7+$`O%]QPO<<GmO$oQPO<<GmOOQO<<Gm<<GmO%OQPO<<GmO%oQPO,59_O%tQPO'#C}O%yQPO1G.xOOQO1G.x1G.xO&RQPO<<GzOOQOAN=XAN=XO%OQPOAN=XO%]QPOAN=XOOQO1G.y1G.yOOQO,59i,59iOOQO-E6{-E6{OOQO7+$d7+$dOOQOAN=fAN=fO%]QPOG22sOOQOG22sG22sOOQOLD(_LD(_",
  stateData: "&W~OtOSPOS~OVTOYUOZUO[UOuPOvQOwROxSO|WO!PYO!Q[O~OrRP~PYOmcOVWXYWXZWX[WXrWXuWXvWXwWXxWX|WX!PWX!QWXzWX{WX~OVUOYUOZUO[UOvQOwROxSOyfO~OVhO~OVUOYUOZUO[UOvQOwROxSO~OrRXzRX{RX~PYOzRP{RP~PYOepO~OzsO{tO~OVwOdxO~OuPO~O}!PO~Od!SO!O!QO~OwRO~OVwO~Od![O!O!QO~O|WO~O",
  goto: "&SrPPPs!V!`!iP#O#fPPP#t#f$V$]$c!`$rPP%O%R!`%X!`%b!`P!`%k%v%|QbOQogQrnQzqQ!OvR!V|_`Oagnqv|__Oagnqv|^VOagnqv|Q}uQ!U{Q!_!WR!`!^^^Oagnqv|SdVeQiZQj]RlciUOVZ]acegnqv|hUOVZ]acegnqv|R!X!PQgVRneQvoR|rQuoQ{rQ!TzQ!W!OR!^!V^XOagnqv|R!]!TRqhQypR!Y!Q_ZOagnqv|_]Oagnqv|[aOgnqv|RkaQeVRmeQ!RyR!Z!R",
  nodeNames: "⚠ LineComment Program Block Atom IfStatement IfKeyword Identifier Expression Boolean String Number MiscOperator TypeAnnotation NotKeyword ThenKeyword ElseKeyword EndKeyword FunctionDeclaration FunctionKeyword ) ( ParameterList Parameter OutputStatement OutputKeyword ReturnStatement ReturnKeyword VariableAssignment AssignmentOperator ExpressionStatement",
  maxTerm: 48,
  nodeProps: [
    ["openedBy", 20,"("],
    ["closedBy", 21,")"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "%}~RcXY!^YZ!^]^!^pq!^rs!ost$]xy$tyz$yz{%O{|%O|}%T}!O%O!P!Q%O!Q![%Y![!]%b!_!`%g!c!}%o#R#S%o#T#o%o~!cSt~XY!^YZ!^]^!^pq!^~!rVOr!ors#Xs#O!o#O#P#^#P;'S!o;'S;=`$V<%lO!o~#^OY~~#aRO;'S!o;'S;=`#j;=`O!o~#mWOr!ors#Xs#O!o#O#P#^#P;'S!o;'S;=`$V;=`<%l!o<%lO!o~$YP;=`<%l!o~$bSP~OY$]Z;'S$];'S;=`$n<%lO$]~$qP;=`<%l$]~$yOe~~%OOd~~%TO[~~%YO!O~~%_PZ~!Q![%Y~%gO}~~%lPm~!_!`%O~%tRV~!c!}%o#R#S%o#T#o%o",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 7, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
