// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,if:78, IF:78, true:80, false:80, Void:82, Int:82, String:82, Boolean:82, not:84, NOT:84, then:86, THEN:86, else:88, ELSE:88, end:90, END:90, function:92, FUNCTION:92, output:98, OUTPUT:98, return:100, RETURN:100}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")xO}QPOOOOQO'#Cb'#CbO#YQPO'#ChOOQO'#Ci'#CiOOQO'#Cm'#CmOOQO'#Cn'#CnOOQO'#Cd'#CdO#aQPO'#CaOOQO'#Cs'#CsO#{QPO'#CrOOQO'#Cw'#CwO$QQPO'#CvOOQO'#Cy'#CyO$QQPO'#CxOOQO'#C|'#C|OOQO'#C`'#C`OOQO'#C}'#C}O$iQPO'#C_QOQPOOO$vQPO,59QO$QQPO,59fO$}QPO'#ChOOQO'#DO'#DOO#aQPO,58{OOQO'#Co'#CoO%UQPO,58{O%`QPO,59^OOQO,59b,59bOOQO,59d,59dOOQO-E6{-E6{OOQO1G.l1G.lO%eQPO1G.lOOQO1G/Q1G/QOOQO-E6|-E6|O%UQPO1G.gO%lQPO1G.gO%tQPO'#CtO%XQPO1G.xOOQO7+$W7+$WO%lQPO7+$ROOQO'#Cp'#CpOOQO'#Cq'#CqO%|QPO7+$RO%XQPO7+$RO&RQPO'#CuOOQO,59`,59`O&WQPO,59`O%oQPO7+$dO%|QPO<<GmO%XQPO<<GmOOQO<<Gm<<GmO%oQPO<<GmO&`QPO,59aO&eQPO'#DPO&jQPO1G.zOOQO1G.z1G.zO&rQPO<<HOOOQOAN=XAN=XO%oQPOAN=XO%|QPOAN=XOOQO1G.{1G.{OOQO,59k,59kOOQO-E6}-E6}OOQO7+$f7+$fOOQOAN=jAN=jO%|QPOG22sOOQOG22sG22sOOQOLD(_LD(_",
  stateData: "&w~OvOSPOS~OVQO^UO_UO`UOwPOxROySOzTO!OWO!RYO!S[O~OtRP~PYOZcOV[X^[X_[X`[Xt[Xw[Xx[Xy[Xz[X!O[X!R[X!S[XX[X|[X}[X~OodO~P!UOVeO^UO_UO`UOxROySOzTO{hO~OVjO~OVeO^UO_UO`UOxROySOzTO~OtRX|RX}RX~PYOXnO~PYO{[X~P!UO|RP}RP~PYOZtO~OXvO~PYO|xO}yO~OV|OX}O~OwPO~O!P!UO~OX!XO!Q!VO~OySO~OV|O~OX!aO!Q!VO~O!OWO~O",
  goto: "&ltPPPu!X!d!oP#WP#pP#p#pPPP$Q#p$e$k$q!d%Q%`%c!d%i!d%t!dP!d&P&`&fQbOQsiQwrQ!PuQ!T{R![!Rc`Oacioru{!Rc_Oacioru{!RbVOacioru{!RQ!SzQ!Z!QQ!d!]R!e!cb^Oacioru{!RSfVgQkZQl]RpdmUOVZ]acdgioru{!RlUOVZ]acdgioru{!RR!^!UQiVRrgQ{sR!RwQzsQ!QwQ!Y!PQ!]!TR!c![bXOacioru{!RR!b!YRujQ!OtR!_!VcZOacioru{!Rc]Oacioru{!R[aOiru{!RSmaoRocQgVRqgQ!W!OR!`!W",
  nodeNames: "⚠ LineComment Program Block Atom IfStatement IfKeyword Identifier Expression ) CallExpression ( ReferenceEpxression Boolean String Number MiscOperator TypeAnnotation NotKeyword ThenKeyword ElseKeyword EndKeyword FunctionDeclaration FunctionKeyword ParameterList Parameter OutputStatement OutputKeyword ReturnStatement ReturnKeyword VariableAssignment AssignmentOperator ExpressionStatement",
  maxTerm: 50,
  nodeProps: [
    ["openedBy", 9,"("],
    ["closedBy", 11,")"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "%}~RcXY!^YZ!^]^!^pq!^rs!ost$]xy$tyz$yz{%O{|%O|}%T}!O%O!P!Q%O!Q![%Y![!]%b!_!`%g!c!}%o#R#S%o#T#o%o~!cSv~XY!^YZ!^]^!^pq!^~!rVOr!ors#Xs#O!o#O#P#^#P;'S!o;'S;=`$V<%lO!o~#^O^~~#aRO;'S!o;'S;=`#j;=`O!o~#mWOr!ors#Xs#O!o#O#P#^#P;'S!o;'S;=`$V;=`<%l!o<%lO!o~$YP;=`<%l!o~$bSP~OY$]Z;'S$];'S;=`$n<%lO$]~$qP;=`<%l$]~$yOZ~~%OOX~~%TO`~~%YO!Q~~%_P_~!Q![%Y~%gO!P~~%lPo~!_!`%O~%tRV~!c!}%o#R#S%o#T#o%o",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 7, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
