import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginReact from "eslint-plugin-react";

export default [
    { files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"] },
    // generated by lezer-generator, and the build output
    { ignores: ["build/", "src/pages/editor/parser.js"] },
    { languageOptions: { globals: { ...globals.browser, ...globals.jest } } },
    pluginJs.configs.recommended,
    ...tseslint.configs.recommended,
    pluginReact.configs.flat.recommended,
    // react is not imported to write jsx since react 17
    pluginReact.configs.flat["jsx-runtime"],
    {
        settings: { react: { version: "detect" } },
        rules: {
            // formatting is prettier's (see .prettierrc); eslint's own indent
            // rule disagrees with it and would fight it
            "@typescript-eslint/no-unused-vars": [
                "error",
                { argsIgnorePattern: "^_" },
            ],
        },
    },
];
