// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Atom = 3,
  Identifier = 4,
  Boolean = 5,
  Keyword = 6,
  TypeAnnotation = 7,
  String = 8,
  Number = 9,
  Operator = 10
