// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,if:92, IF:92, true:94, false:94, Void:96, Int:96, String:96, Boolean:96, not:98, NOT:98, then:100, THEN:100, else:102, ELSE:102, end:104, END:104, function:106, FUNCTION:106, output:112, OUTPUT:112, return:114, RETURN:114, loop:116, LOOP:116, for:118, FOR:118, from:120, FROM:120, to:122, TO:122, while:124, WHILE:124}
export const parser = LRParser.deserialize({
  version: 14,
  states: "+jQYQPOOOOQO'#Ca'#CaO#XQPO'#CgOOQO'#Ch'#ChOOQO'#Cl'#ClOOQO'#Cm'#CmOOQO'#Cc'#CcO#`QPO'#C`OOQO'#Cs'#CsO#zQPO'#CrOOQO'#Cw'#CwO$PQPO'#CvOOQO'#Cy'#CyO$PQPO'#CxOOQO'#C{'#C{O$hQPO'#DPOOQO'#DT'#DTOOQO'#C_'#C_OOQO'#DU'#DUQYQPOOO$pQPO,59PO$PQPO,59mO$wQPO'#CgOOQO'#DV'#DVO#`QPO,58zOOQO'#Cn'#CnO%RQPO,58zO%]QPO,59^OOQO,59b,59bOOQO,59d,59dOOQO'#C|'#C|O%bQPO,59fOOQO'#DQ'#DQO$PQPO,59kOOQO-E7S-E7SOOQO1G.k1G.kO%gQPO1G.kOOQO1G/X1G/XOOQO-E7T-E7TO%RQPO1G.fO%nQPO'#CoO%xQPO1G.fO&QQPO'#CtO%UQPO1G.xO&YQPO1G/QO%UQPO1G/VOOQO7+$V7+$VO%xQPO7+$QOOQO'#Cp'#CpOOQO'#Cq'#CqOOQO7+$Q7+$QO%UQPO7+$QO&_QPO'#CuOOQO,59`,59`O&dQPO,59`O%{QPO7+$dOOQO'#C}'#C}O$PQPO7+$lO%{QPO7+$qOOQO<<Gl<<GlO%UQPO<<GlO%{QPO<<GlO&lQPO,59aO&qQPO'#DWO&vQPO1G.zOOQO1G.z1G.zOOQO<<HO<<HOO'OQPO<<HWOOQO<<H]<<H]O%{QPOAN=WOOQOAN=WAN=WOOQO1G.{1G.{OOQO,59r,59rOOQO-E7U-E7UOOQO7+$f7+$fOOQO'#DO'#DOO$PQPOAN=rOOQOG22rG22rO%UQPOG23^O%{QPOLD(xOOQO!$'Ld!$'Ld",
  stateData: "'T~O}OSPOS~OUQO]UO^UO_UO!OPO!PRO!QSO!RTO!VWO!YYO!Z[O![^O~OYdOUZX]ZX^ZX_ZX{ZX!OZX!PZX!QZX!RZX!VZX!YZX!ZZX![ZXWZX!TZX!UZX~OveO~P!QOUfO]UO^UO_UO!PRO!QSO!RTO!SiO~OUkO~OUfO]UO^UO_UO!PRO!QSO!RTO~O!]nO!`pO~OWsO~PYO!SZX!_ZX~P!QO!TcP!UcP~PYOYzO~OU|O~OW!OO~PYO!TcX!UcX~PYO!T!QO!U!RO~OU!UOW!VO~O!^!YO~O!W!`O~OW!cO!X!aO~O!QSO~OU!UO~OW!lO!X!aO~O!_!mO~O",
  goto: "(Y{PPP|![!jP!xP#nP#n#nPPP$U#n$o$u%[%b![%w&V&Y![&`![&n![&|'['_'b!['e![P!['h'|(SibOcdjtwx{}!T!^!piaOcdjtwx{}!T!^!piVOcdjtwx{}!T!^!ph`Ocdjtwx{}!T!^!pSgVhQlZQm]QueQ}qQ!e!ZR!p!nyUOVZ]cdehjqtwx{}!T!Z!^!n!pxUOVZ]cdehjqtwx{}!T!Z!^!n!pR!i!`QjVRwhQyjQ!PwQ!X{Q![}Q!_!TQ!g!^R!q!pQ!TyR!^!PQ!SyQ!]!PQ!d!XQ!f![Q!h!_Q!o!gR!r!qiXOcdjtwx{}!T!^!pR{kQ!WzR!j!aiZOcdjtwx{}!T!^!pi]Ocdjtwx{}!T!^!pi_Ocdjtwx{}!T!^!pRo_R!Z|R!n!eRq_QcOUrctxQtd_xjw{}!T!^!pQhVRvhQ!b!WR!k!b",
  nodeNames: "⚠ LineComment Program Atom IfStatement IfKeyword Identifier Expression ) CallExpression ( ReferenceEpxression Boolean String Number MiscOperator TypeAnnotation NotKeyword ThenKeyword Block ElseKeyword EndKeyword FunctionDeclaration FunctionKeyword ParameterList Parameter OutputStatement OutputKeyword ReturnStatement ReturnKeyword ForStatement LoopKeyword ForKeyword FromKeyword ToKeyword WhileStatement WhileKeyword VariableAssignment AssignmentOperator ExpressionStatement",
  maxTerm: 62,
  nodeProps: [
    ["openedBy", 8,"("],
    ["closedBy", 10,")"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "%}~RcXY!^YZ!^]^!^pq!^rs!ost$]xy$tyz$yz{%O{|%O|}%T}!O%O!P!Q%O!Q![%Y![!]%b!_!`%g!c!}%o#R#S%o#T#o%o~!cS}~XY!^YZ!^]^!^pq!^~!rVOr!ors#Xs#O!o#O#P#^#P;'S!o;'S;=`$V<%lO!o~#^O]~~#aRO;'S!o;'S;=`#j;=`O!o~#mWOr!ors#Xs#O!o#O#P#^#P;'S!o;'S;=`$V;=`<%l!o<%lO!o~$YP;=`<%l!o~$bSP~OY$]Z;'S$];'S;=`$n<%lO$]~$qP;=`<%l$]~$yOY~~%OOW~~%TO_~~%YO!X~~%_P^~!Q![%Y~%gO!W~~%lPv~!_!`%O~%tRU~!c!}%o#R#S%o#T#o%o",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 6, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
